### ISSUE TITLE
စကား‌‌ပြောနဲ့စကားပြေ

### ISSUE THREAD

**Issue by sisminnmaw** [fossmyanmar/docker-quick-start#2]
Docker Compose,Docker Compose Example နဲ့ တခြားစာမျက်နှာတွေက ရေးနည်းကွာနေလားလို့
report လုပ်တာပါ

**Comment by naingaungphyo** [comment]
Thanks for report.
I noticed that when I was checking for typos. And now fixed them too by [#4 ](https://github.com/fossmyanmar/docker-quick-start/pull/4)
Please close this after PR merge. @kokoye2007
